language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "deployment-exercise-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: mighty-meadow-15696
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: JIXI73YiY7o4EFbj6TbJi53DREcXToCDUCFEqWrqWLoPnd10sCwWezyYf+N+tTJtGV1OHOK1mKhlJ5ze1zmXzDS4jZtCYSjf+ZM5hBU9akVhxZRUlpbn/O7fJWRRnt2tWcHeosr98EEuincy5huUkUO/CEBzkyV4f4xjwEPRyOsOYxuGdQWXKKFomuUB3Z0oR11BE2Bny5LwoJCfSrO9Ka+tf/nnIsMGDQij2sL/sbIdMW1Xl5kEH2LM2hOcg3wRDI+MSySt2SwMDZoSmVyGy1DgZAuSLmDj71j2JDFSIYzHsqwx9tVj08VhjnKiwxhJgn1jwhvcYGs8J/YS+LYjLvg6oSQ0EhP0Prr3BB3pUcdnWP1z4J6rpSdfwXpwt9gEU69Muvz3AAu032tMQwCpbbPd1AordKLAHMcKtD/SiWW51eEl1yGxz716zxKEaw7/20vQNe77zduF1UEw0+d96Z3vBJy5yGGYP/nOhk4oQkkTNWEHUW13ag/gteX4jttn5DBAsXHA3vUYUfoYD1/H1WFLHKZzwEohefRwTqh1vLE/w4dMPBRKW0OluRgGf+/5kygm3Za5DChKAv9nJn2TxUCU+Uualeni18fS2eaZNqUq7RgzSnbPnSHQoBxIpC4Io6d6XQa7YTD7EaNDQ4fmJYiiXRcubufG+bLB8ujSzWc=
